config/routes.rb
Rails.application.routes.draw do
  get 'posts/new' => 'posts#new'
  post '/posts' => 'posts#create'
  get '/posts' => 'posts#index'
  get '/posts/:id' => 'posts#show', as: 'post'
  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id/' => 'posts#destroy', as: 'destroy_post'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
    @post = Post.new
    @post.title = params[:title]
    @post.body = params[:body]
    @post.save
    redirect_to post_path(@post.id)
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:title]
    @post.body = params[:body]
    @post.save
    redirect_to post_path(@post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>投稿を編集する</h1>
<%= form_tag update_post_path(@post.id), method: 'patch' do %>
  <%= text_field_tag :title, @post.title %>
  <%= text_area_tag :body, @post.body %>
  <%= submit_tag '保存' %>
<% end %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
  <p>タイトル</p>
  <span><%=link_to post.title, post_path(post.id) %></span>
<% end %>
<%= link_to "新規作成", posts_new_path, class: "btn edit-btn" %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_tag posts_path do %>
タイトル
  <input type="text" name="title">
本文
  <textarea name="body"></textarea>
  <input type="submit" value="投稿する">
<% end %>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title%></p>
<h2>本文</h2>
<p><%= @post.body %></p>
<%= link_to "編集", edit_post_path(@post.id), class: "btn edit-btn" %>
<%= link_to "削除", destroy_post_path(@post.id), method: 'delete', class: "btn destroy-btn", "data-confirm" => "本当に削除しますか？" %>